### PR TITLE
Ratted

### PR DESCRIPTION
**Pull request by Spinyfish**
Ee aa oo yy uu

### CODE REVIEW

**Comment by ElectrumIsPog** [comment]
https://open.spotify.com/track/5cXtT63OTadsjqfRkm5Dwd?si=176ab4cf3f964bfe

**Comment by ElectrumIsPog** [comment]
Code review complete, good for merge 👍

**Comment by ElectrumIsPog** [comment]
Code review complete, good for merge 👍

**Comment by ElectrumIsPog** [comment]
Code review complete, good for merge 👍

**Comment by ElectrumIsPog** [comment]
Code review complete, good for merge 👍

**Comment by ElectrumIsPog** [comment]
Code review complete, good for merge 👍

**Comment by Briiqn** [comment]
holy ship shut the duck up

**Pull request closed without merging**
